variable "ami" {}
variable "instance_type" {}
variable "key_pair" {}
variable "subnet" {}
variable "environment" {}
variable "vpc_id" {}
variable "client" {}
variable "server" {}
variable "security_group {}"
